name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  appwrite: ^13.0.0
  get: ^4.6.6
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5
  flutter_localizations:
    sdk: flutter
  email_validator: ^3.0.0
  device_info_plus: ^10.1.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.2.3
  image_picker: ^1.1.1
  image_cropper: ^5.0.1
  package_info_plus: ^8.0.2
  flutter_app_badge: ^2.0.2
  flutter_image_compress: ^2.0.4
  share_plus: ^7.0.0
  validators: ^3.0.0
  html_unescape: ^2.0.0
  flutter_local_notifications: ^15.0.0
  path_provider: ^2.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dart_code_metrics: ^4.19.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/planets/
